yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments',
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Поле не заполнено')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, User, Group, Follow
from .forms import PostForm, CommentForm


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user
    ).exists()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    posts = Post.objects.all()
    post = posts.get(pk=post_id)
    comments = post.comments.all()
    count_posts_author = posts.filter(author=post.author).count()
    form = CommentForm(
        request.POST or None
    )
    context = {
        'count_posts_author': count_posts_author,
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_edit_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:profile', request.user)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_edit_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author and not Follow.objects.filter(
            user=request.user,
            author=author
    ).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_edit_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
{% load user_filters %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать пост
              {% else %}
                Новый пост
              {% endif %}
            </div>
            <div class="card-body">
              <form method="post" enctype="multipart/form-data"
                action="{% if is_edit %}{% url 'posts:post_edit' post.pk %}{% else %}{% url 'posts:post_create' %}{% endif %}"
              >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3"
                  {% if field.field.required %}
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}
{% block content %}
  <div class="container py-5">
    <h1>Посты авторов</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author }}
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}

  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества {{ group.title }}{% endblock %}

{% load thumbnail %}
{% block content %}
  <main>
    <div class="container py-5">
      <h1>
        {{ group.title }}
      </h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author }}
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
      <hr>
      {% endif %}
      {% endfor %}

      {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% cache 20 index_page page_obj.number %}
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}

  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% load thumbnail %}
{% load user_filters %}
{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ count_posts_author }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' user %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
         {{ post.text }}
        </p>
        {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
        {% endif %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                 {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
      </article>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}Профайл пользователя {{ author }}{% endblock %}

{% load thumbnail %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя  {{ author }}</h1>
        <h3>Всего постов: {{ page_obj.paginator.count }}</h3>
        {% if request.user.is_authenticated and request.user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >Отписаться</a
            >
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >Подписаться</a
            >
        {% endif %}
      {% endif %}
      </div>
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      <hr>
      {% endfor %}

      {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
{% endblock %}